// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALHFcDVJsYlXyQhV7x5nNIjKnf5ZjxeWc',
    appId: '1:3029053632:web:6dcf82c1b6fcd6392c3d25',
    messagingSenderId: '3029053632',
    projectId: 'vitalfitness-bc7e7',
    authDomain: 'vitalfitness-bc7e7.firebaseapp.com',
    storageBucket: 'vitalfitness-bc7e7.firebasestorage.app',
    measurementId: 'G-WG63789KXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA58ES07vN6dRxQKlRPHHA5cLQZEyuIbV8',
    appId: '1:3029053632:android:a4db44b5bb382f052c3d25',
    messagingSenderId: '3029053632',
    projectId: 'vitalfitness-bc7e7',
    storageBucket: 'vitalfitness-bc7e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZQV2NVw30hg4AnB4nHGUiCd2-t--h2JY',
    appId: '1:3029053632:ios:1b1850c77de022352c3d25',
    messagingSenderId: '3029053632',
    projectId: 'vitalfitness-bc7e7',
    storageBucket: 'vitalfitness-bc7e7.firebasestorage.app',
    iosBundleId: 'com.example.app01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZQV2NVw30hg4AnB4nHGUiCd2-t--h2JY',
    appId: '1:3029053632:ios:1b1850c77de022352c3d25',
    messagingSenderId: '3029053632',
    projectId: 'vitalfitness-bc7e7',
    storageBucket: 'vitalfitness-bc7e7.firebasestorage.app',
    iosBundleId: 'com.example.app01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALHFcDVJsYlXyQhV7x5nNIjKnf5ZjxeWc',
    appId: '1:3029053632:web:a29ede4747949f492c3d25',
    messagingSenderId: '3029053632',
    projectId: 'vitalfitness-bc7e7',
    authDomain: 'vitalfitness-bc7e7.firebaseapp.com',
    storageBucket: 'vitalfitness-bc7e7.firebasestorage.app',
    measurementId: 'G-QKP6RG7KT3',
  );
}
